/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    EmptyData: typeof import('./src/components/EmptyData.vue')['default']
    LeadStatus: typeof import('./src/components/LeadStatus.vue')['default']
    LoadingData: typeof import('./src/components/LoadingData.vue')['default']
    LoadingError: typeof import('./src/components/LoadingError.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TableLoader: typeof import('./src/components/TableLoader.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UiSearch: typeof import('./src/components/UiSearch.vue')['default']
  }
}
